# Recalling Numpy Array Slicing and Indexing

In [79]:
import numpy as np

In [80]:
#create array
x = np.asarray(range(1,26), np.int8).reshape(5,5)

In [81]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

## Slice first 3 elements

<img src="https://github.com/keuperj/DataEngineering22/blob/main/week_1/IMG/np01.png?raw=1">

In [82]:
sliced3 = x[0, :3]
sliced3

array([1, 2, 3], dtype=int8)

##  Slice first 8 elements

<img src="https://github.com/keuperj/DataEngineering22/blob/main/week_1/IMG/np02.png?raw=1">

In [83]:
sliced8 = x.reshape(-1)[:8]
sliced8

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

## Skip every other element

<img src="https://github.com/keuperj/DataEngineering22/blob/main/week_1/IMG/np03.png?raw=1">

In [84]:
skipped = x[0, :5:2]
skipped

array([1, 3, 5], dtype=int8)

## Slice first column

<img src="https://github.com/keuperj/DataEngineering22/blob/main/week_1/IMG/np04.png?raw=1">

In [85]:
firstCol = x[0:4, 0]
firstCol

array([ 1,  6, 11, 16], dtype=int8)

## Slice a diagonal

<img src="https://github.com/keuperj/DataEngineering22/blob/main/week_1/IMG/np05.png?raw=1">

In [86]:
diagonal = np.diagonal(x)
diagonal

array([ 1,  7, 13, 19, 25], dtype=int8)

## Repeat the first element

<img src="https://github.com/keuperj/DataEngineering22/blob/main/week_1/IMG/np06.png?raw=1">

In [87]:
repeated = x[0,0].repeat(5)
repeated

array([1, 1, 1, 1, 1], dtype=int8)

## Simple 2D slicing

<img src="https://github.com/keuperj/DataEngineering22/blob/main/week_1/IMG/np07.png?raw=1">

In [88]:
sliced2d = x[:3,:4]
sliced2d

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]], dtype=int8)

## Slice a zigzag 

<img src="https://github.com/keuperj/DataEngineering22/blob/main/week_1/IMG/np08.png?raw=1">

In [97]:
from numpy.lib.stride_tricks import as_strided
zigzag = np.asarray(range(1,26), np.int32).reshape(5,5)
as_strided(x, shape=(4,2), strides=(48,8))


array([[1, 9],
       [5, 1],
       [4, 5],
       [3, 1]], dtype=int8)

## Sparse slicing

<img src="https://github.com/keuperj/DataEngineering22/blob/main/week_1/IMG/np09.png?raw=1">

In [90]:
sparse = x[0:5:2, :5:2]
sparse

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]], dtype=int8)

## Transpose a 2D array

<img src="https://github.com/keuperj/DataEngineering22/blob/main/week_1/IMG/np10.png?raw=1">

In [91]:
transpose = np.transpose(x[:3,:3])
transpose

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13]], dtype=int8)

## Repeat the first column 4 times


<img src="https://github.com/keuperj/DataEngineering22/blob/main/week_1/IMG/np11.png?raw=1">

In [92]:
firstCol = np.reshape(x[:5,0].repeat(4), (-1, 4))
firstCol

array([[ 1,  1,  1,  1],
       [ 6,  6,  6,  6],
       [11, 11, 11, 11],
       [16, 16, 16, 16],
       [21, 21, 21, 21]], dtype=int8)

## Reshape 1D array to 2D array

<img src="https://github.com/keuperj/DataEngineering22/blob/main/week_1/IMG/np12.png?raw=1">

In [93]:
x = np.asarray(range(1,13), np.int64)
print(x)
np.reshape(x, (-1, 3))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Collapse an axis from a 3D array

<img src="https://github.com/keuperj/DataEngineering22/blob/main/week_1/IMG/np13.png?raw=1">

In [94]:
x = np.asarray(range(1,13), np.int8).reshape(3,2,2)
print(x)
x.reshape(3,-1)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int8)